[target.x86_64-unknown-linux-gnu]                                                                   
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "--cfg", "tokio_unstable"]

[target.aarch64-apple-darwin]                                                                   
rustflags = ["--cfg", "tokio_unstable"]
